apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ml-service
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8000
  selector:
    app: {{ .Release.Name }}-ml-service